app/blueprints/administrator/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from app.models import User, Post
from flask_login import login_required, current_user
from functools import wraps
from app.forms import AdminUserUpdateForm, AdminUserCreateForm
from app import db

administrator_blueprint = Blueprint('administrator', __name__, template_folder='templates')

def admin_login_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_admin():
            return abort(403)
        return func(*args, **kwargs)
    return decorated_view

@administrator_blueprint.route('/administrator')
@login_required
@admin_login_required
def home_admin():
    return render_template('administrator/admin-home.html')


@administrator_blueprint.route('/administrator/users-list')
@login_required
@admin_login_required
def users_list_admin():
    users = User.query.all()
    return render_template('administrator/users-list-admin.html', users=users)


@administrator_blueprint.route('/administrator/create-user', methods=['GET', 'POST'])
@login_required
@admin_login_required
def user_create_admin():
    form = AdminUserCreateForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        hashed = bcrypt.generate_password_hash(password).decode('utf-8')
        admin = form.admin.data
        user = User(username=username, email=email, password_hash=hashed, admin=admin)
        db.session.add(user)
        db.session.commit()
        flash("User added")
        return redirect(url_for('administrator.home_admin'))

    return render_template('administrator/user-create-admin.html', form=form)


@administrator_blueprint.route('/administrator/update-user/<id>', methods=['GET', 'POST'])
@login_required
@admin_login_required
def user_update_admin(id):
    form = AdminUserUpdateForm()
    user = User.query.filter_by(id=id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.admin = form.admin.data
        db.session.commit()
        flash("User was updated", category="info")
        return redirect(url_for('administrator.home_admin'))

    return render_template('administrator/user-update-admin.html', form=form, user=user)


@administrator_blueprint.route('/administrator/delete-user/<id>')
@login_required
@admin_login_required
def user_delete_admin(id):
    user = User.query.get(id)
    db.session.delete(user)
    db.session.commit()
    flash("User was deleted", category="info")
    return render_template('administrator/admin-home.html')

app/blueprints/administrator/templates/administrator/admin-home.html
{% extends "layout.html" %}
{% block content %}
<h1>Welcome to the Admin Demo</h1>
<h3>Hey Admin</h3>


<li><a href="{{ url_for('administrator.users_list_admin') }}">List of all users</a></li>
<li><a href="{{ url_for('administrator.user_create_admin') }}">Create a new user</a></li>
<li><a href="{{ url_for('auth.logout') }}">Click there to logout</a></li>





{% endblock %}

app/blueprints/administrator/templates/administrator/user-create-admin.html
{% extends "layout.html" %}
{% block content %}

{% from "_render_field.html" import render_field %}
        <form action="{{url_for('administrator.user_create_admin')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.email) }}
            {{ render_field(form.password) }}
            {{ render_field(form.password_confirm) }}
            {{ render_field(form.admin) }}
            <p>{{ form.submit(class='btn btn-primary') }}</p>
        </form>



{% endblock %}

app/blueprints/administrator/templates/administrator/user-update-admin.html
{% extends "layout.html" %}
{% block content %}

{% from "_render_field.html" import render_field %}
        <form action="{{url_for('administrator.user_update_admin', id=user.id)}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.email) }}
            {{ render_field(form.admin) }}
            <p>{{ form.submit(class='btn btn-primary') }}</p>
        </form>



{% endblock %}

app/blueprints/administrator/templates/administrator/users-list-admin.html
{% extends "layout.html" %}
{% block content %}

<table border="1" width="100%" cellpadding="5">
    <tr>
     <th>ID</th>
     <th>Username</th>
     <th>Is Admin?</th>
     <th></th>
     <th></th>
    </tr>
    {% for user in users %}
    <tr>
        <th>{{user.id}}</th>
        <th>{{user.username}}</th>
        <th>{{user.admin}}</th>
        <th> <a href="{{url_for('administrator.user_update_admin', id=user.id)}}" class="btn btn-primary">Edit</a></th>
        <th><a href="{{url_for('administrator.user_delete_admin', id=user.id)}}" class="btn btn-primary">Delete</a></th>
       </tr>


    {% endfor %}

    <li><a href="{{ url_for('administrator.home_admin') }}">Back</a></li>


{% endblock %}