app/blueprints/post/views.py
from flask import Blueprint, redirect, request, render_template, flash, url_for, current_app
from app.models import User, Post
from app import db
from app.forms import PostForm, UpdatePostForm
from flask_login import login_required, current_user
from datetime import datetime
from config import ROWS_PER_PAGE


post_blueprint = Blueprint('posts', __name__, template_folder='templates')


@post_blueprint.route('/posts',methods=['GET', 'POST'])
def posts():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.timestamp.desc())

    page = request.args.get('page', 1, type=int)
    posts = posts.paginate(page=page, per_page=ROWS_PER_PAGE)
    
    return render_template('post/posts.html', posts=posts, q=q)

@post_blueprint.route('/post/new', methods=['GET', 'POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.body.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Post was created", category="info")
        return redirect(url_for('posts.posts'))

    return render_template('post/create_post.html', form=form)

@post_blueprint.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    form = UpdatePostForm()

    if current_user.username != post.author.username:
        flash("Its not your post", category="eror")
        return redirect(url_for('posts.posts'))

    elif form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.updatetime = datetime.utcnow()
        db.session.commit()
        flash("Post was updated", category="info")
        return redirect(url_for('posts.post', post_id=post.id))

    elif "delete" in request.form:
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted", category="eror")
        return redirect(url_for('posts.posts'))

    return render_template('post/post.html', post=post, form=form)


@post_blueprint.route('/post/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    pass

app/blueprints/post/templates/post/create_post.html
{% extends "layout.html" %}

{% block content %}
{% from "_render_field.html" import render_field %}
        <form action="{{url_for('posts.add_post')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.title) }}
            {{ render_field(form.body) }}
            <p>{{ form.submit(class='btn btn-primary') }}</p>
        </form>
{% endblock %}

app/blueprints/post/templates/post/post.html
{% extends "layout.html" %}

{% block content %}
<form action="{{url_for('posts.post', post_id=post.id)}}" method="post" novalidate>
  <input type="submit" name="delete" value="Delete Post">
</form>
    <div class="card text-center">
        <div class="card-header">
            {{post.author.username}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{post.body}}</p>
        </div>
        <div class="card-footer text-muted">
          Posted: {{post.timestamp}} Updated: {{post.updatetime}}
        </div>
      </div>

      <h4> Update post </h4>
      {% from "_render_field.html" import render_field %}
        <form action="{{url_for('posts.post', post_id=post.id)}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.title) }}
            {{ render_field(form.body) }}
            <p>{{ form.submit(class='btn btn-primary') }}</p>
        </form>
{% endblock %}

app/blueprints/post/templates/post/posts.html
{% extends "layout.html" %}

{% block content %}
{% if current_user.is_authenticated %}
    <li><a href="{{ url_for('posts.add_post') }}">New post</a></li>
            
    {% endif %}
    <form>
      <input type='text', name='q',  {% if request.args.get('q') != None %}
      value="{{request.args.get('q')}}" {%endif%}>
      <button type='submit'> Search</button>
    </form>
    {% for post in posts.items %}
    <div class="card text-center">
        <div class="card-header">
            {{post.author.username}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{post.body}}</p>
          {% if current_user.username == post.author.username %}
        <a href="{{url_for('posts.post', post_id=post.id)}}" class="btn btn-primary">change</a>
        {% endif %}
        </div>
        <div class="card-footer text-muted">
          Posted: {{post.timestamp}} Updated: {{post.updatetime}}
        </div>
      </div>

    {% endfor %}

    <!-- Pagination Links-->
<div class="text-right">
  <a href="{{ url_for('posts.posts', page=posts.prev_num, q=q) }}"
     class="btn btn-outline-dark 
     {% if posts.page == 1 %}disabled{% endif %}">
      &laquo;
  </a>
<!-- Loop through the number of pages to display a link for each-->
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
          {% if posts.page == page_num %}
          <a href="{{ url_for('posts.posts', page=page_num, q=q) }}"
             class="btn btn-dark">
              {{ page_num }}
          </a>
          {% else %}
          <a href="{{ url_for('posts.posts', page=page_num, q=q) }}"
             class="btn btn-outline-dark">
              {{ page_num }}
          </a>
          {% endif %}
      {% else %}
          ...
      {% endif %}
  {% endfor %}
  <a href="{{ url_for('posts.posts', page=posts.next_num, q=q) }}"
     class="btn btn-outline-dark 
     {% if posts.page == posts.pages %}disabled{% endif %}">
      &raquo;
  </a>
</div>
<p class="text-right mt-3">
 Showing page {{ posts.page }} of {{ posts.pages }}
</p>
{% endblock %}