app/blueprints/accaunt/views.py
from flask import Blueprint, request, url_for, render_template
from flask_login import current_user, login_required 
from app.forms import UpdateAccountForm
import os


accaunt_blueprint = Blueprint('account', __name__, template_folder='templates')

@accaunt_blueprint.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_me = form.about_me.data
        if form.old_password.data:
            current_user.password_hash = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
        db.session.commit()
        flash('Your account has been updated!', 'success')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me
    image_file = url_for('static', filename='images/thumbnails/' + current_user.image_file)
    return render_template('accaunt/account.html', title='Account', image_file=image_file, form=form, user=current_user)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = f_name + random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/images/thumbnails/', picture_fn)
    # form_picture.save(picture_path)

    output_size = (128, 128)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

app/blueprints/general/views.py
from flask import Blueprint, render_template

general_blueprint = Blueprint('general', __name__, template_folder='templates')
@general_blueprint.route('/')
def to_main():
	return render_template('layout.html')

app/templates/_render_field.html
{% macro render_field(field) %}

 <dt>{{ field.label }}
 <dt>{{ field(class='form-control') }}
{% if field.errors %}
        {% for error in field.errors %}
            <span style="color: red;">{{ error }}</span>
         {% endfor %}
{% else %}
<br>
{% endif %}

{% endmacro %}

app/templates/edit.html
{% extends 'admin/model/edit.html' %}

{% block tail %}
    {{ super() }}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Flask app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">   
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

  </head >

  <body>
    
    <header>
      
      <div class="container">
        <h1 class="logo">your advertising could be here</h1>
        {% for cat, msg in get_flashed_messages(True) %}
    <ul class="list-group">
        <li class="list-group-item list-group-item-{{cat}}">{{msg}}</li>
    </ul>
    {%endfor %}
        <strong><nav>
          <ul class="menu">
            {% if current_user.is_anonymous %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.register') }}">register</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.register') }}">register</a></li>
            <li><a href="{{ url_for('account.account') }}">account</a></li>
            <li><a href="{{ url_for('auth.logout') }}">logout</a></li>
            
            {% endif %}
            <li><a href="{{ url_for('general.to_main') }}">main</a></li>
            <li><a href="{{ url_for('posts.posts') }}">posts</a></li>

          </ul>
        </nav></strong>
      </div>
    </header>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>